services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    network_mode: host
    command: postgres -c 'max_connections=58'
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8000M
  app:
    build:
      context: .
    command: /bin/sh start_server.sh
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 16000M
    network_mode: host

volumes:
  pgdata:
