services:
  app:
    build:
      context: .
    command: /bin/sh start_server.sh
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16000M
    network_mode: host
